#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

User.where(email: "caterpiller@gmail.com").each do |user|
  user.send_notification!
  print "#{Time.now} Sent email with notifications to #{user.email}\n"
end
